# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/sander/UnrealEngine_5_8_1

TARGETS = \
	PolySnapSandbox-Android-DebugGame  \
	PolySnapSandbox-Android-Development  \
	PolySnapSandbox-Android-Shipping  \
	PolySnapSandbox-Linux-DebugGame  \
	PolySnapSandbox-Linux-Development  \
	PolySnapSandbox-Linux-Shipping  \
	PolySnapSandbox-LinuxArm64-DebugGame  \
	PolySnapSandbox-LinuxArm64-Development  \
	PolySnapSandbox-LinuxArm64-Shipping  \
	PolySnapSandbox \
	PolySnapSandboxEditor-Linux-DebugGame  \
	PolySnapSandboxEditor-Linux-Development  \
	PolySnapSandboxEditor \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend PolySnapSandboxEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug PolySnapSandboxEditor-Linux-Debug


PolySnapSandbox-Android-DebugGame:
	 $(BUILD) PolySnapSandbox Android DebugGame  -Project="/home/sander/dev/unreal/PolySnap/PolySnapSandbox.uproject" $(ARGS)

PolySnapSandbox-Android-Development:
	 $(BUILD) PolySnapSandbox Android Development  -Project="/home/sander/dev/unreal/PolySnap/PolySnapSandbox.uproject" $(ARGS)

PolySnapSandbox-Android-Shipping:
	 $(BUILD) PolySnapSandbox Android Shipping  -Project="/home/sander/dev/unreal/PolySnap/PolySnapSandbox.uproject" $(ARGS)

PolySnapSandbox-Linux-DebugGame:
	 $(BUILD) PolySnapSandbox Linux DebugGame  -Project="/home/sander/dev/unreal/PolySnap/PolySnapSandbox.uproject" $(ARGS)

PolySnapSandbox-Linux-Development:
	 $(BUILD) PolySnapSandbox Linux Development  -Project="/home/sander/dev/unreal/PolySnap/PolySnapSandbox.uproject" $(ARGS)

PolySnapSandbox-Linux-Shipping:
	 $(BUILD) PolySnapSandbox Linux Shipping  -Project="/home/sander/dev/unreal/PolySnap/PolySnapSandbox.uproject" $(ARGS)

PolySnapSandbox-LinuxArm64-DebugGame:
	 $(BUILD) PolySnapSandbox LinuxArm64 DebugGame  -Project="/home/sander/dev/unreal/PolySnap/PolySnapSandbox.uproject" $(ARGS)

PolySnapSandbox-LinuxArm64-Development:
	 $(BUILD) PolySnapSandbox LinuxArm64 Development  -Project="/home/sander/dev/unreal/PolySnap/PolySnapSandbox.uproject" $(ARGS)

PolySnapSandbox-LinuxArm64-Shipping:
	 $(BUILD) PolySnapSandbox LinuxArm64 Shipping  -Project="/home/sander/dev/unreal/PolySnap/PolySnapSandbox.uproject" $(ARGS)

PolySnapSandbox: PolySnapSandbox-Linux-Development

PolySnapSandboxEditor-Linux-DebugGame:
	 $(BUILD) PolySnapSandboxEditor Linux DebugGame  -Project="/home/sander/dev/unreal/PolySnap/PolySnapSandbox.uproject" $(ARGS)

PolySnapSandboxEditor-Linux-Development:
	 $(BUILD) PolySnapSandboxEditor Linux Development  -Project="/home/sander/dev/unreal/PolySnap/PolySnapSandbox.uproject" $(ARGS)

PolySnapSandboxEditor: PolySnapSandboxEditor-Linux-Development

ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/sander/dev/unreal/PolySnap/PolySnapSandbox.uproject" -Game 

.PHONY: $(TARGETS)
