# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/sander/UnrealEngine_5_8_1

TARGETS = \
	Construction-Android-DebugGame  \
	Construction-Android-Development  \
	Construction-Android-Shipping  \
	Construction-Linux-DebugGame  \
	Construction-Linux-Development  \
	Construction-Linux-Shipping  \
	Construction-LinuxArm64-DebugGame  \
	Construction-LinuxArm64-Development  \
	Construction-LinuxArm64-Shipping  \
	Construction \
	ConstructionEditor-Linux-DebugGame  \
	ConstructionEditor-Linux-Development  \
	ConstructionEditor \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ConstructionEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ConstructionEditor-Linux-Debug


Construction-Android-DebugGame:
	 $(BUILD) Construction Android DebugGame  -Project="/home/sander/dev/unreal/Construction/Construction.uproject" $(ARGS)

Construction-Android-Development:
	 $(BUILD) Construction Android Development  -Project="/home/sander/dev/unreal/Construction/Construction.uproject" $(ARGS)

Construction-Android-Shipping:
	 $(BUILD) Construction Android Shipping  -Project="/home/sander/dev/unreal/Construction/Construction.uproject" $(ARGS)

Construction-Linux-DebugGame:
	 $(BUILD) Construction Linux DebugGame  -Project="/home/sander/dev/unreal/Construction/Construction.uproject" $(ARGS)

Construction-Linux-Development:
	 $(BUILD) Construction Linux Development  -Project="/home/sander/dev/unreal/Construction/Construction.uproject" $(ARGS)

Construction-Linux-Shipping:
	 $(BUILD) Construction Linux Shipping  -Project="/home/sander/dev/unreal/Construction/Construction.uproject" $(ARGS)

Construction-LinuxArm64-DebugGame:
	 $(BUILD) Construction LinuxArm64 DebugGame  -Project="/home/sander/dev/unreal/Construction/Construction.uproject" $(ARGS)

Construction-LinuxArm64-Development:
	 $(BUILD) Construction LinuxArm64 Development  -Project="/home/sander/dev/unreal/Construction/Construction.uproject" $(ARGS)

Construction-LinuxArm64-Shipping:
	 $(BUILD) Construction LinuxArm64 Shipping  -Project="/home/sander/dev/unreal/Construction/Construction.uproject" $(ARGS)

Construction: Construction-Linux-Development

ConstructionEditor-Linux-DebugGame:
	 $(BUILD) ConstructionEditor Linux DebugGame  -Project="/home/sander/dev/unreal/Construction/Construction.uproject" $(ARGS)

ConstructionEditor-Linux-Development:
	 $(BUILD) ConstructionEditor Linux Development  -Project="/home/sander/dev/unreal/Construction/Construction.uproject" $(ARGS)

ConstructionEditor: ConstructionEditor-Linux-Development

ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/sander/dev/unreal/Construction/Construction.uproject" -Game 

.PHONY: $(TARGETS)
