// Copyright (c) 2026, Alexander Verbeek. All rights reserved.

#pragma once

#include "CoreMinimal.h"
#include "PolySnapTypes.h"

/**
 * The socket maths of README sections 2.3 and 2.5. Pure: transforms in, transforms out, no
 * engine state, no world. This is the part Milestone 1 exists to prove, and it is deliberately
 * reachable from an automation spec without spawning anything.
 *
 * Every function here obeys CONVENTIONS.md section 2: Outward is socket-local +X, Tangent is
 * socket-local MINUS Y, Normal is +Z, and Unreal's cross product gives Normal == Tangent ^
 * Outward rather than the other way round.
 */
class POLYSNAP_API FPolySnapGeometry
{
public:
	/** Resolves a socket transform into its three named directions. Scale is ignored; it must be 1. */
	[[nodiscard]] static FPolySnapSocketBasis BasisFromTransform(const FTransform& SocketTransform);

	/**
	 * Rebuilds a socket transform from a basis, the inverse of BasisFromTransform.
	 *
	 * Used to turn a desired mating pose back into a transform. The axis assignment is the
	 * convention read backwards: X is Outward, Y is -Tangent, Z is Normal.
	 */
	[[nodiscard]] static FTransform TransformFromBasis(const FPolySnapSocketBasis& Basis);

	/**
	 * The signed dihedral from Anchor to Other, about the anchor's tangent, over [0, 360).
	 *
	 *     theta = atan2( (Outward_A ^ Outward_B) . Tangent_A,  Outward_A . Outward_B )
	 *
	 * 180 degrees is coplanar; 0 and 360 are both fully closed, reached from opposite sides.
	 *
	 * Deliberately not symmetric in its arguments. Measuring from the other socket's basis
	 * returns the same angle for an aligned pair and 360 - theta for a flipped one, so naming
	 * the anchor as the reference is what makes the angle single-valued at all.
	 *
	 * A signed range is necessary rather than tidy: the unsigned angle between two Outward
	 * vectors spans only 0-180 and reports theta and 360 - theta identically, collapsing
	 * concave corners onto convex ones.
	 */
	[[nodiscard]] static double DihedralDegrees(const FPolySnapSocketBasis& Anchor, const FPolySnapSocketBasis& Other);

	/**
	 * The world basis a held socket must take to mate with Anchor at the given polarity and
	 * dihedral. Positions coincide, tangents are collinear, and Outward is swept about the
	 * shared edge by theta.
	 */
	[[nodiscard]] static FPolySnapSocketBasis MatedBasis(const FPolySnapSocketBasis& Anchor, EPolySnapPolarity Polarity,
		double InDihedralDegrees);

	/**
	 * The world transform a piece must take so that one of its sockets mates with an anchor.
	 *
	 * README section 2.5: exactly one socket pair is the anchor, and the piece's transform is
	 * solved from the anchor and from nothing else. The result is a pure function of the anchor,
	 * the polarity and the dihedral -- which is also what lets a server re-derive it instead of
	 * trusting a client transform.
	 *
	 * @param HeldSocketLocal  The held socket's transform relative to its piece.
	 * @param Anchor           The target socket's basis, in world space.
	 * @param Polarity         Which way round the held piece ends up.
	 * @param InDihedralDegrees The angle about the shared edge.
	 */
	[[nodiscard]] static FTransform SolvePieceTransform(const FTransform& HeldSocketLocal,
		const FPolySnapSocketBasis& Anchor, EPolySnapPolarity Polarity, double InDihedralDegrees);

	/**
	 * The dihedral that puts the held piece closest to the orientation it is already in, for one
	 * polarity. README section 2.5's player-driven reading: the nearest point on the constraint
	 * manifold to the piece's current pose, so the player turns the piece roughly the way they
	 * want it and the snap commits to that reading.
	 *
	 * Closed form, not a search. The admissible poses are a one-parameter family generated by
	 * rotation about the fixed world axis Tangent_A, so the optimum is the twist of the relative
	 * rotation about that axis -- one swing-twist decomposition.
	 *
	 * @param OutRequiredRotationDegrees How far the piece still has to turn once that theta is
	 *                                   applied. This is the number the polarity choice compares.
	 */
	[[nodiscard]] static double NearestDihedralDegrees(const FTransform& HeldSocketLocal,
		const FTransform& CurrentPieceTransform, const FPolySnapSocketBasis& Anchor, EPolySnapPolarity Polarity,
		double& OutRequiredRotationDegrees);

	/**
	 * Picks the polarity and dihedral nearest the piece's current orientation, over both
	 * polarities. Both are always admissible (README section 2.3), so this is the whole of the
	 * flip decision and the reason no explicit flip control exists.
	 */
	static void SolveNearestPlacement(const FTransform& HeldSocketLocal, const FTransform& CurrentPieceTransform,
		const FPolySnapSocketBasis& Anchor, EPolySnapPolarity& OutPolarity, double& OutDihedralDegrees,
		double& OutRequiredRotationDegrees);

	/** The tangent a held socket must end up with, for a polarity. Aligned means opposed. */
	[[nodiscard]] static FVector MatedTangent(const FPolySnapSocketBasis& Anchor, EPolySnapPolarity Polarity)
	{
		return Polarity == EPolySnapPolarity::Aligned ? -Anchor.Tangent : Anchor.Tangent;
	}

	/** Geodesic angle between two rotations, in degrees. The measure "least rotation" is least by. */
	[[nodiscard]] static double AngleBetweenDegrees(const FQuat& A, const FQuat& B);

	/** Wraps an angle in degrees into [0, 360). */
	[[nodiscard]] static double WrapDegrees(double Degrees);
};
